language: ruby
env:
  - MELBOURNE_SPEC_VERSION=1 RUBYLIB=lib:.
  - MELBOURNE_SPEC_VERSION=1 RUBYLIB=.
script: bundle exec mspec spec
rvm:
  - 2.0.0
  - rbx-2
matrix:
  exclude:
    - rvm: ruby-head
      env: MELBOURNE_SPEC_VERSION=1 RUBYLIB=lib:.
    - rvm: rbx-2
      env: MELBOURNE_SPEC_VERSION=1 RUBYLIB=.
